### PR TITLE
Proposal: Filter out inactive witnesses from display on the list

### PR DESCRIPTION
**Pull request by aphelionz**

### CODE REVIEW

**Comment by baabeetaa** [comment]
this page shows witnesses sorted by votes. maybe make it as an option to hide disabled witnesses.

**Comment by aphelionz** [comment]
Yeah I think it's fine to let people keep their votes, and they can rejoin the witness list if they reactivate. That's all fine. you could even maintain the numbering 22, 23, 24, *27*, 28, 29, *31*, etc...

**Comment by graylan0** [comment]
It's been tossed around that votes could reset over a certain period of time. But i think for now just a simple UI change like baabeetaa suggested would be ideal.

**Comment by anxiousstoner** [comment]
The problem with this commit is that ppl won't know to unvote disabled witnesses which is very important.

**Pull request closed without merging**
